### PR TITLE
Fix resolving volume windows path through open() on non windows

### PR DESCRIPTION
**Pull request by MStoykov**
The fix is very, bad, but anything more complicated will likely need way
more testing and will have way too many corner cases.

### CODE REVIEW

**Comment by MStoykov** [comment]
```shell
$ tree -r
.
├── t.go
├── C:\whatabout\this\
└── C:
    └── or
        └── this

2 directories, 3 files
$ cat t.go
package main

import (
        "fmt"
        "io/ioutil"
)

func main() {
        value, err := ioutil.ReadFile("C:\\whatabout\\this\\")
        fmt.Println(string(value), err)
        value, err = ioutil.ReadFile("C:/or/this")
        fmt.Println(string(value), err)
}
$ cat C:\\whatabout\\this\\
wat???
$ cat C:/or/this
batman
$ go run t.go
wat???
 <nil>
batman
 <nil>
```

**Comment by na--** [comment]
I'm confused by your previous comment

**Comment by MStoykov** [comment]
my point is that any kind of absolute windows path can also be a valid Linux file/path-to-file , so I now start to believe a better short term solution will be to warn people that this will probably not work and propose that 
1. they don't use absolute filenames as they are not only hard to part between OSes but also between machines
2. use file:// if they absolutely must have

**Comment by MStoykov** [comment]
We should probably do the same as in c2e19d92 but for the `open` code ?

**Pull request closed without merging**
