### PR TITLE
Update Sobek and fix http.File to not use []byte

### PR DESCRIPTION
**Pull request by mstoykov**
## What?

Update Sobek

## Why?

Sobek updates bring fixes from goja for:
- nesting of destructuring with arrays
- using slices from go code in js code

Also fix for async errors in modules triggering the promise rejection tracker as well, which will be needed for top-level-await

The changes to handling of slices did break some tests and showcased that k6 was handling `http.File().data` badly. Previously it was `[]byte` which it really shouldn't be.

This fix makes certain that the provided input is `string` or `ArrayBuffer` and keeps it that way until it needs to be written.

This aligns with the documentation as well as removes a source of pure `[]byte` in js code which there shouldn't be any.

Separate PR should be made to drop being able to use `common.ToBytes` with `[]byte` as that should never happen and should be 100% a bug.

Also made the go code return a pointer as that just makes sense instead of a struct that will get copied.

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added tests for my changes.
- [x] I have run linter locally (`make lint`) and all checks pass.
- [x] I have run tests locally (`make tests`) and all tests pass.
- [ ] I have commented on my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by oleiade — APPROVED** [review]
Cheers for the detailled explanation 🙇🏻

**Review by olegbespalov — APPROVED** [review]

**Comment by manjunadh5369** [comment]
import { FormData } from 'https://jslib.k6.io/formdata/0.0.2/index.js'

Let  documentFile = http.get( <first api>)

const fd = new FormData();
 fd.append('file', http.file(documentFile.body, `${<file Name>}`, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'));

let response = http.put(<second api>, fd.body(), {headers: {Content-Type': 'multipart/form-data; boundary=' + fd.boundary}})

My code used to work earlier now after this release its working in the opensource k6 but failing in the grafana cloud with following error: {"statusCode":406,"error":"Not Acceptable","message":"The document appears to be corrupted and cannot be loaded."}

It appears that there may be a discrepancy in how file uploads are handled between the open-source version of k6 and Grafana Cloud, particularly after the recent release. Any guidance or updates regarding this issue would be greatly appreciated.

**Comment by mstoykov** [comment]
My expectation is that if you set the response to be binary on the request getting the document it will work again. 

Can you try it? 

You need to set the request [params](https://grafana.com/docs/k6/latest/javascript-api/k6-http/params/) to have `responseType` equal to `binary`

**Comment by manjunadh5369** [comment]
Thank you very much @mstoykov! It's working now.

**Comment by mstoykov** [comment]
Glad I could help. 

To be honest I expect that before that thsi request was jsut a touch corrupted as going to string and back to binary as you did before this last change likely broke the file underneed.

I guess your API either doesn't check the send API *that* carefully, you were *very* lucky for the transition to be lossless, or the response is actually text and your API just expects it as binary data for some reason.

**Pull request merged**
