### PR TITLE
k6/net/grpc: initialize grpc from a protoset

### PR DESCRIPTION
**Pull request by jklipp**
This adds a LoadProtoset function to parse a protoset file to initialize
a grpc client.

In some cases it's easier to produce and consume a single protoset file
than multiple protos and import paths.

Closes https://github.com/grafana/k6/issues/2700.

### CODE REVIEW

**Comment by jklipp** [comment]
Adjusted tests to use a single service with a dependent proto, such that the client shouldn't load unless it's able to see both of those protos in the protoset.  Multiple services was causing random ordering issues that led to not matching the expected order of MethodInfos in tests (possibly due to putting the FileDescriptorProtos into a map in NewFiles on FileOptions?).

**Review by mstoykov — APPROVED** [review]
LGTM! 

Thanks a lot for the excellent PR :tada:

**Comment by mstoykov** [comment]
I added `documentattion-needed` - it will be nice if we can at least open an issue on k6-docs when we merge this

**Review by oleiade — APPROVED** [review]
LGTM 👍🏻 

Sorry my late review, I completely missed the notification 🤦🏻

**Pull request merged**
