### PR TITLE
cmd/relnot: Release notes generator

### PR DESCRIPTION
**Pull request by codebien**
## What?

It picks a list of merged pull requests for a specific milestone adding them to an `unreleased.md` file. The final vision is to run this script once a week (e.g. on Monday) - before manually for the first cycle then automatically from a GitHub Action generating a pull request for amending the `unreleased.md` file.

## Why?

It reduces the effort of manually generating and syncing the release notes, forcing each contributor to write individually the changelog of each PR. It is built on our current template as we want to keep writing release notes for humans.

### CODE REVIEW

**Comment by oleiade** [comment]
I just gave this a shot on my Mac locally, and I got an error, which if I understand this properly, means no `unreleased.md` file ended up being put in the `release notes` folder 😄 

```
Unreleased file descriptor opened
Pull requests fetched: 40

2023/10/04 09:43:43 Parsing changes from Pull request:
#3355 #3351 #3347 #3346 #3344 #3343 #3342 #3341 #3340 #3339 #3338 #3337 #3336 #3335 #3334 #3332 #3327 #3324 #3323 #3321 #3320 #3317 #3311 #3308 #3302 #3300 #3299 #3291 #3290 #3289 #3288 #3284 #3283 #3279 #3276 #3275 #3272 #3271 #3234 #3200

Matching stage report:
Type: undefined, Count: 25, Pulls: [3355 3340 3336 3334 3332 3327 3324 3323 3321 3320 3317 3311 3302 3300 3299 3291 3290 3284 3279 3276 3275 3272 3271 3234 3200]
Type: internal, Count: 7
Type: breaking, Count: 3
Type: bug, Count: 3
Type: epic-feature, Count: 1
Type: ux, Count: 1
Moving the new unreleased version failed: rename /var/folders/7m/pwyxs26d0vq4ckzp8b0017vw0000gn/T/3692441298 ./../../release notes/unreleased.md: no such file or directory
```

**Review by olegbespalov — COMMENTED** [review]
First of all, thanks for doing this! :bow: 

My main question is, why should the tool's code be in the k6 repository? 

Even if it aims solely to serve grafana/k6 repo, it still sounds more like a mini-repository that could be well-organized and follow its structure: README, CODEOWNERS, DEPENDENCIES, and so on.

**Comment by olegbespalov** [comment]
@codebien I see that you closed the PR. Could you please also comment for the reference why you did that or maybe what are the next steps here. Thanks!

**Comment by codebien** [comment]
Hey @olegbespalov, I just closed it as it isn't in our current priorities. I may restore it the next time I will be the release driver. If in the meantime, someone else needs/wants to use or expand it, feel free to go ahead.

**Pull request closed without merging**
