### PR TITLE
Update `github.com/jhump/protoreflect`

### LINKED ISSUE #3331: Go install k6 broken and linter issues
### Brief summary

Running `go install go.k6.io/k6` results in an error due to a dependency on `github.com/jhump/protoreflect`. The latest version from this repository appears to have fixed the issue - https://github.com/jhump/protoreflect/issues/566

Additionally, and maybe related, running `golangci-lint` is also broken. Potentially due to the previous failures?

### k6 version

v0.46.0

### OS

macOS

### Docker version and image (if applicable)

_No response_

### Steps to reproduce the problem

Run `go install go.k6.io/k6`
Run `golangci-lint run --fix -E gci,godot,gofumpt,misspell,whitespace,gosec` 

### Expected behaviour

Both processes to complete successfully.

### Actual behaviour

`go install go.k6.io/k6`
Results in

```
# github.com/jhump/protoreflect/desc/protoparse
../../go/pkg/mod/github.com/jhump/protoreflect@v1.15.1/desc/protoparse/ast.go:151:12: undefined: ast.OneOfNode
../../go/pkg/mod/github.com/jhump/protoreflect@v1.15.1/desc/protoparse/ast.go:244:47: undefined: ast.OneOfNode
../../go/pkg/mod/github.com/jhump/protoreflect@v1.15.1/desc/protoparse/ast.go:258:53: undefined: ast.OneOfElement
../../go/pkg/mod/github.com/jhump/protoreflect@v1.15.1/desc/protoparse/ast.go:271:1: missing return
../../go/pkg/mod/github.com/jhump/protoreflect@v1.15.1/desc/protoparse/parser.go:257:25: undefined: options.Index
```

`golangci-lint run --fix -E gci,godot,gofumpt,misspell,whitespace,gosec`  Tested with golangci-lint versions `v1.52.2` and `v1.54.2`)

 results in:
```
WARN [runner] Can't run linter goanalysis_metalinter: inspect: failed to load package cmd: could not load export data: no export data for "go.k6.io/k6/cmd" 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: inspect: failed to load package cmd: could not load export data: no export data for "go.k6.io/k6/cmd"
```

### PR DESCRIPTION
**Pull request by olegbespalov**
## What?

This PR updates the `github.com/jhump/protoreflect` to the latest version.

## Why?

The current version could cause the issues described in the #3331.

## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests for my changes.
- [ ] I have run linter locally (`make ci-like-lint`) and all checks pass.
- [x] I have run tests locally (`make tests`) and all tests pass.
- [ ] I have commented on my code, particularly in hard-to-understand areas.

## Related PR(s)/Issue(s)

Closes #3331

### CODE REVIEW

**Review by codebien — COMMENTED** [review]
Is it expected to inlclude the `grpc` bump?

**Comment by mstoykov** [comment]
Can we actually just bump xk6-grpc which already has this bumped ?

**Comment by olegbespalov** [comment]
> Is it expected to inlclude the grpc bump?

yes, since it's a requirement.

> Can we actually just bump xk6-grpc which already has this bumped ?

right, this is the way to go :+1:

**Comment by olegbespalov** [comment]
Closing in favor of #3334

**Pull request closed without merging**
