### PR TITLE
[WIP] Add TimescaleDB collector

### PR DESCRIPTION
**Pull request by robingustafsson**
This PR adds support for a [TimescaleDB](https://www.timescale.com/) collector.

I've included the JSON source for a Grafana dashboard that has a couple of more features than the ones available for InfluxDB:

grafana-open-source-load-testing-stack

With this PR I also propose we make TimescaleDB the "default" collector over InfluxDB for the Docker Compose setup for the following reasons:

- SQL is waay easier and more powerful than InfluxQL, and I personally didn't want to invest the time to learn yet another query language if I would have instead opted for InfluxData's [Flux language](https://github.com/influxdata/flux) that they support in newer versions of InfluxDB.
- TimescaleDB (and PostgreSQL) is something we have much more knowledge about internally than InfluxDB given that we operate TimescaleDB for our cloud service.

TODO:
- [x] ~Figure out how to add [pgx](https://github.com/jackc/pgx) as a dependency as I'm running into issues with `dep ensure` and [the author seems to be suggesting using Go modules](https://github.com/jackc/pgx/issues/628) (related to https://github.com/loadimpact/k6/issues/1070)~
- [ ] Write tests for the collector
- [ ] Write docs for using the collector
- [ ] Publish the Grafana dashboard

### CODE REVIEW

**Comment by idxn** [comment]
Will this be merged anytime soon?

**Comment by iKarthik** [comment]
Is there plans for this PR to be merged? I do not have enough experience with go, otherwise I would love to help here.

**Comment by na--** [comment]
It's not going to be merged for k6 v0.28.0, since that is slated to be released mid-September, but it's very likely to be included in k6 v0.29.0, slated for mid-November (and in `master` before that, depending on when we rebase and merge it).

**Comment by leon-andria** [comment]
It will be helpful to get this new output 👍 
Do we still plan for mid-november to get this PR merged ?

**Comment by na--** [comment]
No, unfortunately we didn't fit this PR in k6 v0.29.0, so it's delayed until the next k6 v0.30.0, sorry

**Comment by 16erik18** [comment]
Still waiting for this to be released

**Comment by na--** [comment]
@16erik18, k6 v0.31.0 added support for output extensions, so it should be easy to pluck the output from this PR and make it into one, if you don't want to wait: https://github.com/k6io/k6/blob/master/release%20notes/v0.31.0.md#output-cleanup-and-extensions-1874

**Review by MStoykov — COMMENTED** [review]
I have left some more comments about minor things, but I haven't run or tested this myself. Either way good job :clap: 

Can you provide any numbers on how it behaves if you load it a lot?

Also maybe we should include the docker-compose.yml file(and the accompanying configuration) here as well ?

**Comment by na--** [comment]
This is now an [xk6](https://github.com/grafana/xk6) extension: https://github.com/grafana/xk6-output-timescaledb

**Pull request closed without merging**
