### PR TITLE
SBOM

### PR DESCRIPTION
**Pull request by SadFaceSmith**
Quick PR to add SBOM report generation on release. We (Security Engineering) have this running in grafana/grafana and grafana/loki. We are planning to expand this to all our OSS Projects.

### CODE REVIEW

**Review by imiric — COMMENTED** [review]
Hi Ethan, thanks for opening this PR!

We weren't familiar with SBOM on the team, and while we can see the benefit, we're wondering how this JSON file is going to be used. It's clearly not meant for human consumption, so will it be scanned by a tool to generate reports, vulnerability detection, etc.? If you can explain a bit more about the process and motivation behind this, we'd be happy to merge it. Thanks!

**Comment by SadFaceSmith** [comment]
> Hi Ethan, thanks for opening this PR!
> 
> We weren't familiar with SBOM on the team, and while we can see the benefit, we're wondering how this JSON file is going to be used. It's clearly not meant for human consumption, so will it be scanned by a tool to generate reports, vulnerability detection, etc.? If you can explain a bit more about the process and motivation behind this, we'd be happy to merge it. Thanks!

Yes, generally customers will ingest these files into a tool to scan for vulnerabilities or OSS licenses that they don't want to use. Or they will convert the JSON file to a CSV for easier reading.

**Review by imiric — APPROVED** [review]

**Review by codebien — APPROVED** [review]

**Comment by olegbespalov** [comment]
It seems like this action [hasn't been triggered](https://github.com/grafana/k6/actions/workflows/sbom-report.yml) because we have a bit non-standard releasing process from our CI :thinking: 

@SadFaceSmith do you expect us to have this artifact attached to the release (e.g. https://github.com/grafana/k6/releases/tag/v0.45.0) right?

**Comment by codebien** [comment]
I guess based on https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release we should trigger on `released` or `published`.

**Pull request merged**
