### PR TITLE
Don't try to assign the author of a PR to review it

### PR DESCRIPTION
**Pull request by mstoykov**

### CODE REVIEW

**Review by olegbespalov — APPROVED** [review]

**Review by olegbespalov — APPROVED** [review]

**Comment by olegbespalov** [comment]
It seems like it hasn't taken into account the assigned reviewers :thinking: 

image

**Comment by mstoykov** [comment]
> It seems like it hasn't taken into account the assigned reviewers

It wasn't doing that even before that I think

**Comment by mstoykov** [comment]
> I think it makes sense to assign only the diff between required and already assigned.

Ah... this will be intrinsically racy - I did assign reviewers after making the PR. The action couldn't know it has to wait for 10 seconds for this. 

I also am very much for first *fixing* the action not actually working in some cases at all then it assigning more people.

**Comment by olegbespalov** [comment]
>Ah... this will be intrinsically racy - I did assign reviewers after making the PR. The action couldn't know it has to wait for 10 seconds for this.

Okay, then it's not critical I belive :+1:

**Review by olegbespalov — APPROVED** [review]

**Review by codebien — APPROVED** [review]

**Pull request merged**
