### PR TITLE
Add test for race in PushIfNotDone

### PR DESCRIPTION
**Pull request by mstoykov**
## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added tests for my changes.
- [ ] I have run linter locally (`make lint`) and all checks pass.
- [ ] I have run tests locally (`make tests`) and all tests pass.
- [ ] I have commented on my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by oleiade — APPROVED** [review]
Nice catch! 🚀

**Review by olegbespalov — CHANGES_REQUESTED** [review]
Waiting for actual fix, or closing the PR

**Review by ankur22 — APPROVED** [review]
LGTM 🚀

**Comment by mstoykov** [comment]
This was a PR to illustrate that there is no way for the current PushIfNotDOne to not race with the context done and channel close.

The thing is that in the current code there is no place where the channel gets closed before every VU has returned so nothing should be using this - which is signaled with the context close.

The "real" fix for this will be to not use close the channel, but that is already used in some places, so it is way more involved.

Again in practice this should never happen - if it does it is a bug in the other code.

**Pull request closed without merging**
