### PR TITLE
Added information about built-in modules for Version command

### PR DESCRIPTION
**Pull request by amelkikh**
Hi!
Please consider to review my PR.
Additional information about built-in modules seems to be helpful when compiled tool shared with teammates.

Have a good day!

### CODE REVIEW

**Review by codebien — CHANGES_REQUESTED** [review]
Hi @amelkikh,
thanks for the effort in doing it :bow: :clap: 

I expect you need this to get information about the extensions included in a binary built with `xk6`. If that is the reason then we share the same feeling. We opened an issue in the past for it #1741.
Ideally, we would prefer to have a broader solution to support any extension (javascript module or output).

I try to summarise the idea for our vision.
When an extension is registered using the [output.RegisterExtension](https://pkg.go.dev/go.k6.io/k6/output#RegisterExtension) / [modules.Register](https://pkg.go.dev/go.k6.io/k6/js/modules#Register) methods then the internal logic should resolve the [PkgPath](https://pkg.go.dev/reflect#Type) using the Go [reflect](https://pkg.go.dev/reflect) package to get the module path of the given object and save it in a (shared) slice. In this way, the slice of resolved extensions can be used for getting the list when the `k6 version` command is invoked and it can be combined with the metadata returned from [debug.BuildInfo](https://pkg.go.dev/debug/buildinfo@go1.19.1#Read) for returning a more detailed list as previewed in the description of #1741.

Let me know if you need more information.

Note: If you are going to submit the requested changes then remember to sign the CLA, please. We will need it signed to eventually approve and merge the PR.

**Comment by amelkikh** [comment]
Hi, @codebien!

Thanks for the detailed explanation. I share this approach with you. 
It will take me some time to figure out how to make a sign and dive into how your project works as I don't have much experience yet.

**Comment by codebien** [comment]
Hi @amelkikh,
did you hit some sort of issues implementing the suggestion? Can I help in some way? Thanks.

**Comment by codebien** [comment]
Hi @amelkikh,
thanks for your commitment and for letting us know. I hope we will see you as a contributor again in the future.

**Pull request closed without merging**
