### PR TITLE
Drop common.Bind and other context-based deprecated utils 

### LINKED ISSUE #2385: Drop common.Bind and context-based utils
Remove the last call of common.Bind from https://github.com/grafana/k6/blob/bee87c5ab7cbbc4e6e288b2d2016139f4af22351/js/initcontext.go#L213

and remove the deprecated APIs - https://github.com/grafana/k6/issues/2344

### LINKED ISSUE #2428: xk6 integration tests are using old JS module and metrics APIs
This needs to be updated to use the new `js`Module` API and create its metric from the `Registry`: https://github.com/grafana/k6/blob/master/.github/workflows/xk6-tests/xk6-js-test/jstest.go

### PR DESCRIPTION
**Pull request by codebien**
Closes  #2385
Closes #2428

### CODE REVIEW

**Comment by MStoykov** [comment]
@codebien I think you will need to fix https://github.com/grafana/k6/issues/2428 as well

**Comment by codebien** [comment]
@MStoykov xk6-tests updated now

**Review by na-- — COMMENTED** [review]
LGTM, though I am pretty sure we can also easily remove `BindToGlobal()`, this is the only place it's used as far as I can see: https://github.com/grafana/k6/blob/03e938d13f2c289e867abe5431f62c950646b477/js/bundle.go#L341-L344

**Comment by MStoykov** [comment]
I think we can do that in a separate PR @na-- - there also likely will be other changes in `js` and `common` after this changes

**Review by MStoykov — APPROVED** [review]

**Review by na-- — APPROVED** [review]
Fair enough :man_shrugging: @codebien, can you please open a separate v0.38.0 issue or PR about that? :pray:

**Comment by codebien** [comment]
@na-- Sure, I'm already on it

**Pull request merged**
