### PR TITLE
NTLM dependency package update to solve a duplicate headers bug upon NTLM authentication

### PR DESCRIPTION
**Pull request by Resousse**
Hello,

A new version of go-ntlmssp has been released following a PR I did, to solve a bug.
The bug is : NTLM authentication doesn't work when two Authorization/WWW-Authenticate headers are returned by the back-end server.
With the new version of the go-ntlmssp package, the number of header doesn't matter, and the most accurate will be taken.

### CODE REVIEW

**Comment by MStoykov** [comment]
Hi @Resousse, thanks for the PR and the change upstream. I haven't checked either one of those, but you currently aren't committing the changes to the `vendor` directory, so you should do that as well ;)

**Review by MStoykov — DISMISSED** [review]
LGTM, thanks for both contributions :bow: 

We have some problems with testing this, so can you confirm that you have tested this experimentally? And if you have a setup that works okay on *linux* it will be really nice as we have been trying to get anything working for test purposes :(

**Comment by Resousse** [comment]
Hello,
Yes, tested on both Windows and MinGW environment, I can confirm it works.
I'm not able to test the NTLM connection on my personal Mac because it works in a secure VPN network, that is deployed on my windows Computer.

**Comment by MStoykov** [comment]
`go mod verify` is failing in the CI

**Comment by Resousse** [comment]
> `go mod verify` is failing in the CI

Sorry @MStoykov  , I forgot one minor label that has been updated prior my change. Tested ok with `go mod vendor` and `go mod verify`.

**Review by MStoykov — APPROVED** [review]

**Review by na-- — APPROVED** [review]

**Pull request merged**
