### PR TITLE
Adding support for overriding grpc authority pseudo header

### PR DESCRIPTION
**Pull request by ali-atac**
## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests for my changes.
- [ ] I have run linter locally (`make lint`) and all checks pass.
- [ ] I have run tests locally (`make tests`) and all tests pass.
- [ ] I have commented on my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by codebien** [comment]
Hey @ali-atac,
it seems a reasonable change as we already discussed in the past.
I see this pull request is in a draft state but at this point, it hasn't changed for some days, let me clarify and remind you that signing the [CLA is required](https://github.com/grafana/k6/blob/38f273d5900cf33d31936a547093ff6acf1a99a9/CONTRIBUTING.md#contributing-to-k6) to be able to merge your contribution.

**Review by codebien — COMMENTED** [review]
Hey @ali-atac,
it seems a reasonable change as we already discussed in the past.
I see this pull request is in a draft state but at this point, it hasn't changed for some days, let me clarify and remind you that signing the [CLA is required](https://github.com/grafana/k6/blob/38f273d5900cf33d31936a547093ff6acf1a99a9/CONTRIBUTING.md#contributing-to-k6) to be able to merge your contribution.

**Comment by ali-atac** [comment]
Thanks for the comment, I'll add some tests next week

**Review by codebien — CHANGES_REQUESTED** [review]
Hi @ali-atac,
#3152 has been merged, so you can now rebase to finalize the code. Are you still interested in working on it?

**Comment by codebien** [comment]
Hey!
I close this pull request because the [offical doc](https://grpc.io/docs/guides/custom-name-resolution/#overview) mentions that `authority` is already a supported case for the `dns://` resolver (the syntax is `dns:[//authority/]host[:port]`). If someone hits an issue with it, a specific bug report or a unit test is necessary before merging any dedicated logic for it.

**Pull request closed without merging**
