### PR TITLE
cmd/convert refactor to not use global variables

### PR DESCRIPTION
**Pull request by MStoykov**

### CODE REVIEW

**Comment by MStoykov** [comment]
This is based on #2334 , but can probably be rebased on origin/master if that becomes an issue.

**Review by codebien — APPROVED** [review]
LGTM

**Review by oleiade — DISMISSED** [review]
"one small step for a ..." 🚀 👍🏻

**Review by codebien — APPROVED** [review]

**Review by oleiade — APPROVED** [review]
👍🏻 🦕

**Pull request merged**
